version: "3.9"

name: services-onest-hrm-service

# Example API for images
services:
  adempiere-database:
    container_name: ${POSTGRES_HOST}
    image: ${POSTGRES_IMAGE}
    restart: ${GENERIC_RESTART}
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./postgresql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgresql/seed.backup:/tmp/seed.backup
      - ./postgresql/after_run:/tmp/after_run
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5432; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'America/Caracas'
      PGTZ: 'America/Caracas'
    networks:
      - shared_network

  adempiere-grpc-server:
    image: ${GRPC_SERVER_IMAGE}
    container_name: ${GRPC_SERVER_HOST}
    restart: ${GENERIC_RESTART}
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/${GRPC_SERVER_PORT}; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    depends_on:
      adempiere-database:
        condition: service_healthy
    secrets:
      - adempiere_db_password
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${GRPC_SERVER_DB_PORT}
      DB_NAME: ${GRPC_SERVER_DB_NAME}
      DB_PASSWORD: ${GRPC_SERVER_DB_PASSWORD}
      # DB_PASSWORD: ${GRPC_SERVER_DB_PASSWORD}
      DB_PASSWORD_FILE: /run/secrets/adempiere_db_password
      JWT_SECRET_KEY: ${GRPC_SERVER_JWT_SECRET_KEY}
    networks:
      - shared_network

  grpc-proxy:
    image: ${GRPC_PROXY_IMAGE}
    container_name: ${GRPC_PROXY_HOST}
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5555; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    ports:
     - ${GRPC_PROXY_BACKEND_PORT}:5555
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/definitions/adempiere-mobile-service.pb:/data/adempiere-grpc-server.pb:ro
    depends_on:
      - adempiere-grpc-server
    networks:
    - shared_network

  adempiere-zk:
    image: ${ADEMPIERE_ZK_IMAGE}
    container_name: ${ADEMPIERE_ZK_HOST}
    restart: ${GENERIC_RESTART}
    ports:
      - ${ADEMPIERE_ZK_PORT}:8080
    secrets:
      - adempiere_db_password
    environment:
      ADEMPIERE_DB_SERVER: ${ADEMPIERE_ZK_DB_HOST}
      ADEMPIERE_DB_PORT: ${ADEMPIERE_ZK_DB_PORT}
      ADEMPIERE_DB_NAME: ${ADEMPIERE_ZK_DB_NAME}
      # ADEMPIERE_DB_PASSWORD: ${ADEMPIERE_ZK_DB_PASSWORD}
      ADEMPIERE_DB_PASSWORD_FILE: /run/secrets/adempiere_db_password
    depends_on:
      adempiere-database:
        condition: service_healthy
    networks:
      - shared_network



networks:
  shared_network:
    name: ${DEFAULT_NETWORK}

volumes:
  volume_postgres:
    name: ${POSTGRES_VOLUME}

secrets:
  adempiere_db_password:
    file: ./secrets/adempiere_db_password.txt
